#VAMOS A ENTENDER QUE SON LAS LISTAS/ARRAY
#SON ES UN VALOR RESERVADO EN LA MEMORIA QUE PUEDE TENER VARIAS VARIABLES, EN POSICIONES
#  VOVALES_POSICIONES = [ 0 , 1, 2, 3, 4, 5]  EMPIEZA DESDE 0

vocales = ["a","e", "i", "o", "u"]

print("MOSTRAR LO QUE TIENE LA LISTA: ", vocales)

print("MOSTRAR LA POSICION 0: ", vocales[0])
print("MOSTRAR LA POSICION 1: ", vocales[1])
print("MOSTRAR LA POSICION 2: ", vocales[2])
print("MOSTRAR LA POSICION 3: ", vocales[3])
print("MOSTRAR LA POSICION 4: ", vocales[4])
#print("MOSTRAR FUE DE RANGO DE LA LISTA EJ 5 : ", vocales[5])

#LA LISTA SE PUEDE MODIFICAR : AÑADIR, QUITAR MODIFICAR, CAMBIAR DATO EN LA POSICON

#1 AÑADIR DATOS A  LA LISTA

vocales.append("á")
print("MOSTRAR LO QUE TIENE LA LISTA NUEVA: ", vocales) #CONTIENE EL Á

#PARA QUITAR LA ULTIMA POSICIOÓN SE UTILZA POP

vocales.pop() #ELIMINARÁ LA LETRA A
print("MOSTRAR LA NUEVA LISTA SIN LA ULTIMA : ", vocales)

#SABER EL LENGTH DE LA LISTA

print ("LENGHT DE LA LISTA: ", len(vocales)) #EL LARGO

#COMPROBAR SI ALGO ESTA EN LA LISTA POR EJ LA é EN LA LSIT

letra = "é"

print("SABER SI LA VARIABLES LETRA ESTÁ DENTRO:", letra in vocales)